### ISSUE TITLE
Silent login is not working with old tokens

### ISSUE THREAD

**Issue by dami-gg** [zalando-incubator/solution-center-login#100]
function silentLogin(email, password, expectOldToken) {
      return service.login(email, password, expectOldToken)
        .then(
          function (token) {
            return handleSessionTokenValidation(token);
          }
        );
    }

service.login can return either an old or a new token and only the new ones are validated. Therefore silentLogin won't store any credentials when using old tokens.

We should handle the validations depending on the expectOldToken variable.

Please check silentLogout just in case we need to do something similar

**Comment by cjhowald** [comment]
After further investigation, it seems that `silentLogin` actually does work correctly. It validates and stores both old and new tokens. The issue reported appears to be a configuration problem in the hosting application. Closing this issue for now. Will reopen if it is still reproducible with correct configuration.
