### ISSUE TITLE
redirection issue

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#11]
I'm testing currently on stage.

Sometimes when I'm not logged in, I got redirected from:
https://insights-frontend-stage.adventure.zalan.do/

to:
https://sc-stage.norris.zalan.do/#/login?redirect=https:%2F%2Finsights-frontend-stage.adventure.zalan.do%2Fanalytics

but then it quickly redirects again to:
https://sc-stage.norris.zalan.do/#/login?redirect=https:%2F%2Fsc-stage.norris.zalan.do%2F%23%2F

which should not happen.

I now can reproduce this issue, for example it happens always when I delete localStorage value:
```solutionCenter-user: null```

**Comment by cjhowald** [comment]
Fixed with #17
