### ISSUE TITLE
logout redirection

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#12]
When I log out, it looks like I'm redirected to sing-on page without "redirect" parameter. So I loose the application context when I want to log in again. Is this a feature or a bug? :)
My opinion is we should preserve the application context, unless a user wants to change it.

**Comment by dami-gg** [comment]
We were wondering the same during the implementation and left it like this for the moment. I'll ask the product guys and change it or not depending on their decision ;)

**Comment by dami-gg** [comment]
Official reply from Stefan and John: "No, we keep them going to our landing page. There will be so many products in the end and might be hard to handle" Problem solved ;)
