### ISSUE TITLE
silentLogin doesn't return promise

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#13]
```
  function silentLogin(email, password) {
    service.login(email, password)
        .then(
            function (token) {
```

and therefore calling it ```silentLogin(e,p).then()``` throws an error.

**Comment by mrac** [comment]
btw logout() and silentLogout() don't return promise either, which will cause the same issues when trying to chain it.

**Comment by dami-gg** [comment]
Yes it makes sense, I've just added them now in version 0.2.4
