### ISSUE TITLE
silentLogin() doesn't work anymore

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#24]
`silentLogin()` function doesn't work properly. It looks like it's broken from version 0.3.0.
We use it for accessing our stage/integration environments locally.

From ver. 0.3.0 silentLogin() returns rejected promise, even though credentials are correct.

We use the following configuration used with ver.2.7.0 (working):

```
    authenticationServiceProvider.configEnvironment('STAGE');
    authenticationServiceProvider.setInternalCommunication(true);
```

For version 0.3.0 and latest (0.5.0) I also experimented with following configuration (but it doesn't work either):

```
    authenticationServiceProvider.configEnvironment('LOCAL', 7777, 'https://tm-stage.norris.zalan.do');
    // with and without:
    authenticationServiceProvider.setInternalCommunication(true);
```

**Comment by mrac** [comment]
There was no issue for integration. Only for stage.

**Comment by cjhowald** [comment]
This issue is now fixed, according to @mrac.
