### ISSUE TITLE
Allow Custom Cookie Domain

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-login#25]
Analytics sometimes runs locally on a mobile device with a domain other than `localhost`. We should allow them to override the cookie domain in `configEnvironment`.

**Comment by cjhowald** [comment]
@greg This should be simple once we merge your communicator changes.

**Comment by gregdeane** [comment]
@cjhowald Indeed it will be.

**Comment by ifadin** [comment]
:+1:

**Comment by mrac** [comment]
I think it's solved and can be closed.
