### ISSUE TITLE
Move Cookie Defaults into Config

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-login#28]
Right now, cookie defaults (domain, secure, expiration) are being set in the solution center. Anyone calling our APIs that set or delete cookies will not have these defaults. This could cause issues, where cookies silently fail to be deleted. We should move these defaults into our config here and remove it from solution center.

```
$cookiesProvider.defaults.domain = environment.cookieDomain;
$cookiesProvider.defaults.expires = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 7);
$cookiesProvider.defaults.secure = environment.name !== 'LOCAL';
```

**Comment by dami-gg** [comment]
Makes total sense to me :+1:
