### ISSUE TITLE
Change angular services naming

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/solution-center-login#30]
authenticationService, ENVIRONMENTS and environmentsService are to common names, there is a risk to overwrite services registered in the user app.

I would suggest to use ```sc``` as a prefix.

authenticationService -> scAuthenticationService
environmentsService -> scEnvironmentsService
ENVIRONMENTS -> SC_ENVIRONMENTS

**Comment by dami-gg** [comment]
@gregdeane

**Comment by gregdeane** [comment]
@rbarilani We are planning to improve our module naming style in the near future. @dami-gg @cjhowald   correct me if I misstate the facts.

We plan on switching to a dot notation style, renaming our modules as `solution.center.xxx`. These changes should alleviate future naming collisions.

I don't have an ETA for the changes but it will likely be sooner rather than later.

**Comment by dami-gg** [comment]
He's talking about the factories names. I agree we should rename those as a client might have also something called authenticationService since it's quite generic name and have a conflict

**Comment by gregdeane** [comment]
Sorry about that. I was thinking factory/et al. names but writing module names. I still think we should use dot notation on our other names as well.

module: `solution.center.xxx`
others: `sc.xxx.xxx` or `solution.center.xxx.xxx`, etc.

**Comment by dami-gg** [comment]
Yes, we have all already agreed on dots for modules You can start using them ;)

**Comment by rbarilani** [comment]
@gregdeane @dami +1 also for module dot naming.

my vote for: sc.xxx or solution-center.xxx

sc or solution-center = namespace

**Comment by gregdeane** [comment]
We are going to use this convention: ScAuthenticationService.

**Comment by sambhav-gore** [comment]
Test Steps:

Make sure logged in user details are displayed in header correctly.
Make sure that the navigation to other modules work correctly (in the same environment).
Make sure that modules are hidden when brand is not selected.

**Comment by sambhav-gore** [comment]
Confirmed test steps are passing.

**Comment by rbarilani** [comment]
> Make sure that modules are hidden when brand is not selected.

@sambhav-gore can you extend this more? (my concern is orders, profile, articlesmodules are not related to any brand....)

**Comment by sambhav-gore** [comment]
@rbarilani My above comment was to only test that the changes done for this issue is not affecting any functionality. Regarding your comment let's discuss this with the UX team (as this was done as part of a different change).

**Comment by rbarilani** [comment]
@sambhav-gore ok thx. I will.
