### ISSUE TITLE
Clear credentials automatically... 

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/solution-center-login#32]
In the function ```handleTokenValidation``` in case of rejection the service clear the credentials in any case and redirect to login.

What if token service respond with 500? the user is logged out also if "is not his fault".

I will check for specific status code = 401

**Comment by sambhav-gore** [comment]
Tested for invalid tokens using following steps:

1. Login to integration.
2. From Chrome Dev tools -> Resources : clear SC_TOKEN within the sc-integration cookie.
3. Try navigating to a brand page or a user page 

It should redirect to login page with credentials cleared.
