### ISSUE TITLE
After log out SC_TOKEN cookie is not deleted

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#35]
Apparently after log out SC_TOKEN cookie is not deleted.

It causes issues in our app, because our interceptor is triggered and handles a case for 'session expiration', which is a different case.

**Comment by mrac** [comment]
@ifadin says it sometimes delete it and sometimes not :)

**Comment by ifadin** [comment]
I was able to reproduce by:

1. Clean SC cookies.
2. Go to https://content-router-stage.adventure.zalan.do/analytics/ and login.
3. Go to https://insights-frontend-stage.adventure.zalan.do/analytics (an app that reverse-proxy is pointing to, the same zalan.do domain).
4. Click logout
5. You are redirected to SC login page and SC_TOKEN cookie is there.

**Comment by cjhowald** [comment]
Cookie defaults (e.g. expiration and secure) are not being set when you login via redirection from an app. This is fixed by #34 which will be merged after go-live.

**Comment by cjhowald** [comment]
Closed by #34
