### ISSUE TITLE
$location.url

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#4]
I use `setSolutionCenterCommunication(true)` for mocked login process. I experienced strange behavior for redirection when `$location.url` is sometimes working and sometimes not.

It's most probably related to a digest cycle, not always being triggered after url change.

Wrapping it in $timeout solves the issue:
```
$timeout(function() {
  $location.url(redirectionPath);
});
```

**Comment by dami-gg** [comment]
We're still not sure this is the right thing to do, could you please try again with the new version 0.1.5?

**Comment by dami-gg** [comment]
This might be a better alternative:

http://www.bennadel.com/blog/2605-scope-evalasync-vs-timeout-in-angularjs.htm

**Comment by mrac** [comment]
Interesting article. I've never used this function. But I used $timeout a lot, and I know it works. So here I have zero experience. The only benefit I see: it might invoke the function faster, in some cases. But there are also a few question marks:

- one guy says (see post of Alejandro Iglesias) that $evalAsync doesn't always guarantee $digest-safe invocation
- there could be some testing problems. With $timeout you can just $timeout.flush()
- $evalAsync is performed on $scope, but in a service you cannot use scope, you can only use root scope. Not sure if it works the same way though. Look here, how $evalAsync functionality differs, depending from where it's called:
http://stackoverflow.com/questions/17301572/angularjs-evalasync-vs-timeout

- documentation of $evalAsync says calling $scope.$apply() is probably needed anyway in some cases. Does it apply to $location.url()? I'm not sure.

  > Note: if this function is called outside of a $digest cycle, a new $digest cycle will be scheduled. However, it is encouraged to always call code that changes the model from within an $apply call. That includes code evaluated via $evalAsync.

**Comment by mrac** [comment]
I tested it, and in our case when I wrap solution-center-login's $location.url() in $timeout() it works, but when I wrap it in $rootScope.$evalAsync() it doesn't work.

**Comment by mrac** [comment]
It also works when I call $timeout in UI-router resolve controller:

```
        resolve: {
            user: function(authenticationService, $timeout) {
                return $timeout(function() {
                    authenticationService.requireAuthenticatedUser();
                });
            }
        }
```

So this is probably better place to fix it than in this library. My guess is it's UI-router that goes out of angular context, not solution-center-login.

**Comment by mrac** [comment]
Actually no :) sorry.
The code above is incorrect, it should have one more "return":

```
        resolve: {
            user: function(authenticationService, $timeout) {
                return $timeout(function() {
                    return authenticationService.requireAuthenticatedUser();
                });
            }
        }
```

But now it doesn't work...

So I found out why, and this is the cause why UI-router loose 'angular context'. 

When you redirect to login page, you reject the promise. But if you reject the promise UI-router will not $apply/$digest it.

Adding this, fixes the issue:
```
    return service.authenticate(encodeURIComponent($window.location.href)).catch(function() {
      return $q.resolve();
    });
```

**Comment by mrac** [comment]
I just point the place. It's not a big help for you, I guess, because rejecting it is what we want to have.

**Comment by cjhowald** [comment]
@mrac Is this issue okay to close, or are you still running into this?

**Comment by mrac** [comment]
Sorry, I accidentally pressed "Close and comment".
The issue still exists.
Just posted a few hints where is the cause of the problem.
