### ISSUE TITLE
Default to last brand

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-login#40]
If a user navigates to CMS or Analytics without selecting a brand, CMS & Analytics automatically choose the first brand alphabetically. This behavior is subtle and unexpected. The user may have to go back to the Solution Center to choose a different brand before continuing. In the worst case, a user could make changes to the wrong brand without realizing.

Note: this only affects users with multiple brands -- primarily internal users.

As discussed in the June 13 meeting with @cjhowald, @gabrielhl, @mrac, and @rbarilani:
To reduce the chance we have to silently select a brand, we should store the last brand in the client (and not clear it on logout as we do for the current brand).
1. When `setBrand` is called, set a `LAST_BRAND` cookie.
2. When `getBrand` is called, first attempt to read from `BRAND`, then `LAST_BRAND`.
3. Do not clear `LAST_BRAND` on logout or when `clearBrand` is called.

This will not guarantee that a brand exists, since the user may be logging in for the first time, or might have cleared their cookies. However, it should default to the last brand in most cases.

Out of scope:
- Handle the case in CMS or Analytics where there is no current or previous brand (e.g. modal asking them to select a brand). This will be tackled separately by CMS & Analytics, with help from us as needed, and does not belong in this service in any case.

**Comment by mrac** [comment]
It should be also taken into account that `LAST_BRAND` value may be not relevant (current user may be different than previously logged-in). I'm not sure if `getBrand` should handle it, or consumers of `getBrand` should be aware of it.

**Comment by mrac** [comment]
For the above reason, I would rather not change `getBrand()`, and introduce another method `getLastBrand()`
- It would not break current functionality
- It would be up to products to use getLastBrand() or be aware that the return value may be invalid

**Comment by rbarilani** [comment]
What if? SC_LAST_BRAND contains something like:

```[{brandId: 3458, uid: 1}, {brandId: 12345, uid: 2}]```

Where uid is the id of the user.

@mrac can solve this issue?

> user may be different than previously logged-in

**Comment by mrac** [comment]
If permissions change in the meantime, it would not solve the issue.

**Comment by rbarilani** [comment]
@mrac if the permission change via solution center, solution center can update that info accordingly?

**Comment by mrac** [comment]
If it's persisted in the database (instead of cookies) then yes. Backend microservice could update it.

But I'm not sure backend is the right place to implement it.

**Comment by rbarilani** [comment]
> But I'm not sure backend is the right place to implement it.

I don't have in mind another solution to share this info across multiple devices.

**Comment by mrac** [comment]
@rbarilani good point

**Comment by cjhowald** [comment]
With the migration to business partners, this issue is obsolete. We will no longer work with brands, and the most recently used business partner(s) will be provided by the backend.
