### ISSUE TITLE
Update Logo to New Zalando Logo

### ISSUE THREAD

**Issue by gabrielhl** [zalando-incubator/solution-center-login#7]
To comply with Zalando's new CI, the logo in the header must be changed
The new logo in SVG format is attached to the issue
[logo.svg.zip](https://github.com/zalando-incubator/solution-center-login/files/246876/logo.svg.zip)

**Comment by dami-gg** [comment]
As you said, that's the header project, not the login ;) I'll move the issue there and close this one

**Comment by gabrielhl** [comment]
There's currently a logo in the login app, needs to be changed as well if it's not pulling the file from header
