### ISSUE TITLE
Support new token service

### ISSUE THREAD

**Issue by dami-gg** [zalando-incubator/solution-center-login#71]
We must discuss and research what's the best way to connect to the new user service which supports business partners, whether to start a new project from scratch or adapt this one, how to do it and also write the following tasks

**Comment by cjhowald** [comment]
This library allows authentication to the new token service via the existing login page, as the API is the same.

There is discussion around how we migrate from the old login to the new. Current ideas are 2 parallel login pages each connected to one token service, or a single hybrid page connected to both.

We are also considering allowing a user to be authenticated against old and new services at the same time (separate logins, but storing both tokens separately). This would require changes to this library to support multiple cookie keys and configuration to control which to use.

I will update further once the design is approved.

**Comment by cjhowald** [comment]
Current design:

> # Single hybrid login page
> 
> ## Overview:
> - Enhance the current login page to allow login to old and new token service.
> - Following migration, disconnect old token service from the login page.
> 
> ## Development:
> - solution-center: Add logic to authenticate against old and new token service
> - solution-center-login 
>   - Update to read from new cookie
>   - Update to use new token service for token verification
