### ISSUE TITLE
Update to New Communicator

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-login#79]
A new version of the communicator with the new service URLs is soon to be released. We need to upgrade to that version for login to work correctly.

We will also need to update `environments-service.js` at the same time:

```js
    function getTokensAPI(environment, useOldToken) {
      if (useOldToken) {
        return environment.TOKEN_SERVICE + '/tokens'; // TODO change to old key
      } else {
        return environment.USER_SERVICE_NEW + '/tokens'; // TODO change to new key
      }
    }
```

**Comment by gregdeane** [comment]
@cjhowald Here's a TS version of the current communicator if you're interested. 

https://github.com/gregdeane/scc-ts

Awesome work on the dual-token login!
