### ISSUE TITLE
Internal communication doesn't work with old token

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#97]
Perhaps because of ```configEnvironment()``` method not setting ```TOKEN_SERVICE_OLD```.

**Comment by cjhowald** [comment]
Good catch. `configEnvironment` only configures the new, not legacy, endpoint. We can enhance `configEnvironment` to respect `shouldUseOldToken`. As an alternative, you can use the `setCurrentEnvironment` function of the communicator with complete flexibility.
