### ISSUE TITLE
No support for old token response

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#99]
Old-token response is the token string.

In new sc-login, ```login()``` method expects it to be an object with properties like: ```state```, ```value``` for valid response and ```reason``` for error. 

Is it a bug, or it won't work with old token?

**Comment by cjhowald** [comment]
The return value of `login` is the same, a resolved promise containing the token string or a rejected promise containing the error.

`state`, `value`, and `reason` are provided by `$q.allSettled`, which aggregates our calls to the old and new endpoints. This is not a bug, and is compatible with both old and new tokens. For more details on `$q.allSettled`, see [here](https://github.com/kriskowal/q/wiki/API-Reference#promiseallsettled).
